SPLIT_KEYBOARD = yes

OLED_ENABLE = no
OLED_DRIVER = SSD1306

AUDIO_ENABLE = no
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

ENCODER_MAP_ENABLE = yes

MOUSEKEY_ENABLE = yes
NO_USB_STARTUP_CHECK = yes
