VIAL_ENABLE = yes
VIA_ENABLE = yes
VIAL_INSECURE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
EXTRAFLAGS+=-flto
MOUSEKEY_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
NO_USB_STARTUP_CHECK = yes
